In [1]:
!pip install numpy

In [2]:
import numpy as np

In [30]:
a=np.array([2,3,4,5,6,4],)

In [18]:
a.reshape(3,2)

array([[2., 3.],
       [4., 5.],
       [6., 4.]])

In [20]:
a.ndim

1

In [22]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
b=np.arange(1,7)

In [32]:
b

array([1, 2, 3, 4, 5, 6])

In [33]:
a+b

array([ 3,  5,  7,  9, 11, 10])

In [34]:
a/b

array([2.        , 1.5       , 1.33333333, 1.25      , 1.2       ,
       0.66666667])

In [35]:
a-b

array([ 1,  1,  1,  1,  1, -2])

In [37]:
np.sqrt(a)

array([1.41421356, 1.73205081, 2.        , 2.23606798, 2.44948974,
       2.        ])

In [39]:
l1=[1,2,3,4,5,6]
l2=[6,5,4,3,2,1]


In [41]:
l3=[(x+y) for x,y in zip(l1,l2)]


In [42]:
l3

[7, 7, 7, 7, 7, 7]

In [49]:
m=np.array([[1,2,3,4],[5,6,7,8],[2,3,4,5],[1,2,3,4],[4,5,6,7],[6,7,8,9]])

In [59]:
m.sum()

112

In [60]:
m

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [2, 3, 4, 5],
       [1, 2, 3, 4],
       [4, 5, 6, 7],
       [6, 7, 8, 9]])

In [61]:
m.sum(axis=0)

array([19, 25, 31, 37])

In [62]:
m.sum(axis=1)

array([10, 26, 14, 10, 22, 30])

In [65]:
#iterate
for i in m:
    print(i)

[1 2 3 4]
[5 6 7 8]
[2 3 4 5]
[1 2 3 4]
[4 5 6 7]
[6 7 8 9]


In [66]:
for i in m:
    for j in i:
        print(j)

1
2
3
4
5
6
7
8
2
3
4
5
1
2
3
4
4
5
6
7
6
7
8
9


In [75]:
m

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [2, 3, 4, 5],
       [1, 2, 3, 4],
       [4, 5, 6, 7],
       [6, 7, 8, 9]])

In [83]:
for x in np.nditer(m,order='F',flags=['external_loop']):
    print(x)

[1 5 2 1 4 6]
[2 6 3 2 5 7]
[3 7 4 3 6 8]
[4 8 5 4 7 9]


In [84]:
a

array([2, 3, 4, 5, 6, 4])

In [85]:
b

array([1, 2, 3, 4, 5, 6])

In [86]:
for x,y in np.nditer([a,b]):
    print(x,y)

2 1
3 2
4 3
5 4
6 5
4 6


In [87]:
m


array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [2, 3, 4, 5],
       [1, 2, 3, 4],
       [4, 5, 6, 7],
       [6, 7, 8, 9]])

In [89]:
m[1,3]

8

In [92]:
m[:,2:4]

array([[3, 4],
       [7, 8],
       [4, 5],
       [3, 4],
       [6, 7],
       [8, 9]])

In [93]:
m

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [2, 3, 4, 5],
       [1, 2, 3, 4],
       [4, 5, 6, 7],
       [6, 7, 8, 9]])

In [95]:
a

array([2, 3, 4, 5, 6, 4])

In [96]:
b

array([1, 2, 3, 4, 5, 6])

In [104]:
m

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [2, 3, 4, 5],
       [1, 2, 3, 4],
       [4, 5, 6, 7],
       [6, 7, 8, 9]])

In [113]:
n=np.hsplit(m,2)

In [114]:
m

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [2, 3, 4, 5],
       [1, 2, 3, 4],
       [4, 5, 6, 7],
       [6, 7, 8, 9]])

In [115]:
b=m>4

In [118]:
np.vstack(m[b])

array([[5],
       [6],
       [7],
       [8],
       [5],
       [5],
       [6],
       [7],
       [6],
       [7],
       [8],
       [9]])

In [110]:
n[0]

array([[1, 2],
       [5, 6],
       [2, 3],
       [1, 2],
       [4, 5],
       [6, 7]])

In [111]:
n[1]

array([[3, 4],
       [7, 8],
       [4, 5],
       [3, 4],
       [6, 7],
       [8, 9]])